mysite/accounts/urls.py
from django.conf.urls import url

from django.urls import path,include,reverse_lazy
from django.conf import settings
from django.conf.urls.static import static

from .views import (
    UserCreateAPIView,
    UserListView,
    UserDetailView,
  
    PasswordChangeView,
    PasswordResetView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    # GoogleRegisterView,
    # GoogleLoginDoneView,
    # GoogleLoginView,
    MyProfileView,

) 

# register_converter(converters.FourDigitYearConverter, 'yyyy')
from rest_framework_simplejwt import views as jwt_views


app_name = 'accounts'
urlpatterns = [
    path('users/', UserListView.as_view(),name='users_list'),

    path('user/', UserDetailView.as_view(),name='users_detail'),
    path('profile/', MyProfileView.as_view(),name='profile'),

  

    # path('login/', GoogleLoginDoneView.as_view(),name='google_login'),
    # path('google/',GoogleRegisterView.as_view(),name='google_register'),
    # path('google/login/',GoogleLoginView.as_view(),name='google_login2'),
    path('register/', UserCreateAPIView.as_view(),name='register'),
    
    path('password/',PasswordChangeView.as_view(),name='change_password'),
    path('reset/', PasswordResetView.as_view(),name='password_reset'),
    path('reset/confirm/<uidb64>/<token>',PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset/complete/',PasswordResetDoneView.as_view(),name='password_reset_complete'),


    path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    
]

mysite/chats/urls.py
from django.urls import path
from .views import *

app_name = 'chats'

urlpatterns = [
    # path('templates', TemplatesList.as_view(),name='template_list'),

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    

    path('admin/', admin.site.urls),
    path('api/v1/', include('accounts.urls')),
    path('api/v1/', include('netizen.urls')),
    path('api/v1/', include('activities.urls')),
    path('api/v1/', include('comments.urls')),
    path('api/v1/report/',include('reports.urls')),
    path('api/v1/',include('chats.urls')),
    path('api/v1/',include('relationships.urls')),
   
]

if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/accounts/forms.py
from django import forms
from django.contrib.auth import (
    authenticate, get_user_model, password_validation,
)


from django.utils.translation import gettext, gettext_lazy as _
class SetPasswordForm(forms.Form):
    """
    A form that lets a user change set their password without entering the old
    password
    """
    error_messages = {
        'password_mismatch': _('The two password fields didn’t match.'),
    }
    new_password1 = forms.CharField(
        label=_("New password"),
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
        strip=False,
        help_text=password_validation.password_validators_help_text_html(),
    )
    new_password2 = forms.CharField(
        label=_("New password confirmation"),
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
    )

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super().__init__(*args, **kwargs)

    def clean_new_password2(self):
        password1 = self.cleaned_data.get('new_password1')
        password2 = self.cleaned_data.get('new_password2')
        if password1 and password2:
            if password1 != password2:
                raise forms.ValidationError(
                    self.error_messages['password_mismatch'],
                    code='password_mismatch',
                )
        password_validation.validate_password(password2, self.user)
        return password2

    def save(self, commit=True):
        password = self.cleaned_data["new_password1"]
        self.user.set_password(password)
        if commit:
            self.user.save()
        return self.user

mysite/accounts/views.py
from django.contrib.auth import get_user_model

User = get_user_model()


from rest_framework import generics
from rest_framework import status
from rest_framework.response import Response

from .serializers import UserSerializer,RegistrationSerializer,PasswordSerializer,UserUpdateSerializer,UserQuerSerializer
from rest_framework.views import APIView
from rest_framework.permissions import AllowAny,IsAuthenticated
from rest_framework.authtoken.models import Token
from django.contrib.auth import password_validation
from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_encode
from django.contrib.sites.shortcuts import get_current_site
from django.template import loader
from django.utils.encoding import force_bytes
from django.core.mail import EmailMultiAlternatives
from django.urls import reverse_lazy
from django.views.generic.edit import FormView
from .forms import SetPasswordForm
from django.utils.translation import gettext_lazy as _
from django.utils.decorators import method_decorator
from django.views.decorators.debug import sensitive_post_parameters
from django.views.decorators.cache import never_cache
from django.core.exceptions import ValidationError
from django.utils.http import  urlsafe_base64_decode
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
INTERNAL_RESET_SESSION_TOKEN = '_password_reset_token'
from rest_framework.pagination import PageNumberPagination
from django.conf import settings

# from google.auth.transport import requests as google_transport_requests
# from google.oauth2 import id_token

from rest_framework_simplejwt.tokens import RefreshToken

from django.views.generic.base import TemplateView
from activities.helpers import update
from rest_framework import filters
from relationships.helpers import get_blockers,get_blocked_users
class UserCreateAPIView(APIView):
	permission_classes = [AllowAny]
	def post(self, request):
		if request.method == 'POST':
			data = {}


			serializer = RegistrationSerializer(data=request.data)
			
			if serializer.is_valid(raise_exception=True):
				user = serializer.save()
			
				token = get_tokens_for_user(user)

				return Response(token,status=status.HTTP_201_CREATED)
			else:
				data = serializer.errors
			return Response(data,status.HTTP_400_BAD_REQUEST)





class PasswordChangeView(APIView):
	permission_classes = [IsAuthenticated]

	def post(self, request, *args, **kwargs):
		current_user = User.objects.get(id=request.user.id)
		serializer = PasswordSerializer(data=request.data)
		if serializer.is_valid():
			# print(serializer.validated_data["new_password"])
			if not current_user.check_password(serializer.validated_data.get("old_password")):
				return Response({"old_password": ["Wrong password."]}, status=status.HTTP_400_BAD_REQUEST)
			new_password = serializer.validated_data.get("new_password")
			new_password2 = serializer.validated_data.get("new_password2")

			if new_password != new_password2:
				return Response({"new_password": ["New passwords must match"]}, status=status.HTTP_400_BAD_REQUEST)

			try:
				password_validation.validate_password(serializer.validated_data.get('new_password'),current_user)
				password_validation.validate_password(serializer.validated_data.get('new_password2'),current_user)
			except ValidationError as e :
				# print(e)
				return Response({"new_password": e.messages}, status=status.HTTP_400_BAD_REQUEST)
			

			current_user.set_password(new_password2)
			current_user.save()
			
			return Response({'response':"password changed successfully"}, status=status.HTTP_200_OK)
		return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class UserListView(generics.ListAPIView):
	permission_classes = [IsAuthenticated]
	filter_backends = [filters.SearchFilter]
	search_fields = ['^username']
	queryset = User.objects.all()
	pagination_class = PageNumberPagination
	pagination_class.page_size = 2
	serializer_class = UserQuerSerializer

	def list(self, request, *args, **kwargs):
		queryset = self.filter_queryset(self.get_queryset())

		queryset = queryset.exclude(id__in=get_blockers(request.user))


		page = self.paginate_queryset(queryset)
		if page is not None:
			serializer = self.get_serializer(page, many=True)
			return self.get_paginated_response(serializer.data)

		serializer = self.get_serializer(queryset, many=True)
		return Response(serializer.data)
	


class UserDetailView(APIView):
	permission_classes = [IsAuthenticated]
	
	def get(self, request, format=None):
		qs = User.objects.all()
		
		username = self.request.query_params.get('username')

		user = get_object_or_404(qs, username=username)
		serializer = UserSerializer(user,context={'request': request })
		return Response(serializer.data)

class MyProfileView(APIView):
	permission_classes = [IsAuthenticated]
	
	def get(self, request, format=None):
		qs = User.objects.all()
		user = get_object_or_404(qs, id= request.user.id,username=request.user.username)
		serializer = UserSerializer(user,context={'request': request})
		# print(user.followers)
		return Response(serializer.data)

	def patch(self, request, *args, **kwargs):
		current_user = User.objects.get(id=request.user.id)
	
		serializer = UserUpdateSerializer(current_user,data=request.data,partial=True)

		if serializer.is_valid():
			if 'username' in request.data:
				update(request.user.username,request.data['username'])

			serializer.save()
			return Response(serializer.data, status=status.HTTP_200_OK)
		else:
			return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
	

	def delete(self, request, *args, **kwargs):

		current_user = User.objects.get(id=request.user.id)
		current_user.delete()

		return Response(status=status.HTTP_204_NO_CONTENT)

class PasswordResetView(APIView):
	permission_classes = [AllowAny]
	def post(self, request, *args, **kwargs):
		use_https = False
		email_template_name = 'password_reset_email.html'
		html_email_template_name = 'password_reset_email_template.html'
		subject_template_name = 'password_reset_subject.txt'
		from_email = None
		token_generator = default_token_generator

		if 'email' not in request.data:
			return  Response({'response':'error'}, status=status.HTTP_400_BAD_REQUEST)


		user_email = request.data['email']
		user =  get_object_or_404(User, email=user_email)
		current_site = get_current_site(request)
		site_name = current_site.name
		domain = current_site.domain
		context = {
			'email': user_email,
			'domain': domain,
			'site_name': site_name,
			'uid': urlsafe_base64_encode(force_bytes(user.pk)),
			'user': user,
			'token': token_generator.make_token(user),
			'protocol': 'https' if use_https else 'http',
			
		}
		self.send_mail(subject_template_name,email_template_name, context, from_email,user_email, html_email_template_name=html_email_template_name,)
		return  Response({'email':"email sent successfully"}, status=status.HTTP_200_OK)

	def send_mail(self, subject_template_name,email_template_name,
				context, from_email, to_email, html_email_template_name=None):

		subject = loader.render_to_string(subject_template_name, context)
		# Email subject *must not* contain newlines
		subject = ''.join(subject.splitlines())
		body = loader.render_to_string(email_template_name, context)
	   
		html_email = loader.render_to_string(html_email_template_name, context)
		email_message = EmailMultiAlternatives(subject, html_email, from_email, [to_email])
	
	


		email_message.send()


class PasswordResetConfirmView( FormView):
    form_class = SetPasswordForm
    post_reset_login = False
    post_reset_login_backend = None
    reset_url_token = 'set-password'
    success_url = reverse_lazy('accounts:password_reset_complete')
    template_name = 'password_reset_confirm.html'
    title = _('Enter new password')
    token_generator = default_token_generator

    @method_decorator(sensitive_post_parameters())
    @method_decorator(never_cache)
    def dispatch(self, *args, **kwargs):
        assert 'uidb64' in kwargs and 'token' in kwargs

        self.validlink = False
        self.user = self.get_user(kwargs['uidb64'])

        if self.user is not None:
            token = kwargs['token']
            if token == self.reset_url_token:
                session_token = self.request.session.get(INTERNAL_RESET_SESSION_TOKEN)
                if self.token_generator.check_token(self.user, session_token):
                    # If the token is valid, display the password reset form.
                    self.validlink = True
                    return super().dispatch(*args, **kwargs)
            else:
                if self.token_generator.check_token(self.user, token):
                    # Store the token in the session and redirect to the
                    # password reset form at a URL without the token. That
                    # avoids the possibility of leaking the token in the
                    # HTTP Referer header.
                    self.request.session[INTERNAL_RESET_SESSION_TOKEN] = token
                    redirect_url = self.request.path.replace(token, self.reset_url_token)
                    return HttpResponseRedirect(redirect_url)

        # Display the "Password reset unsuccessful" page.
        return self.render_to_response(self.get_context_data())

    def get_user(self, uidb64):
        try:
            # urlsafe_base64_decode() decodes to bytestring
            uid = urlsafe_base64_decode(uidb64).decode()
            user = User._default_manager.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist, ValidationError):
            user = None
        return user

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.user
        return kwargs

    def form_valid(self, form):
        user = form.save()
        del self.request.session[INTERNAL_RESET_SESSION_TOKEN]
        # if self.post_reset_login:
			

mysite/accounts/templates/base.html
{% load static %}

<html>

<head>

 
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

<!-- JS, Popper.js, and jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>


  {% block javascript %}
  {% endblock %}

  {% block stylesheet %}
  {% endblock %}

</head>

<body>

  <div class="container-fluid pt-5">
  {% block content %}
  {% endblock %}
</div>
</body>


</html>

mysite/accounts/templates/base_accounts.html
{% extends 'base.html' %}

{% load static %}

{% block stylesheet %}

{% endblock %}

{% block body %}
  <div class="container">
    <h1 class="text-center logo my-4">
  
    </h1>
    {% block content %}
    {% endblock %}
  </div>
{% endblock %}

mysite/accounts/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sign In</title>
    <script src="https://apis.google.com/js/platform.js" async defer></script>
    <meta name="google-signin-client_id" content="266064661203-rhv67sjobavgeuhq9jvqjuiiqdensho7.apps.googleusercontent.com">
</head>
    <div class="g-signin2" data-onsuccess="onSignIn" data-theme="dark"></div>
    <br/>
    <input type="button" onclick="signOut();" value="Sign out"/>
      <form id="myForm"  method="post">
    username: <input type="text" name="fname">
      pass 1: <input type="text" name="pass1">
        pass 2: <input type="text" name="pass2">

    <input type="submit" value="Submit">
    </form>
</body>
<script>
    var id_token;
    function onSignIn(googleUser) {
        console.log("Sign in successful! Yay!");
        id_token = googleUser.getAuthResponse().id_token;
 
    }
    function signOut() {
        var auth2 = gapi.auth2.getAuthInstance();
        auth2.signOut().then(function () {
          console.log('User signed out.');
        });
    }


    var form = document.getElementById('myForm');

// Adds a listener for the "submit" event.
form.addEventListener('submit', function(e) {

  e.preventDefault();
  var x = form["fname"].value;
  var pass1 = form["pass1"].value;
  var pass2  = form["pass2"].value;

       let xhr = new XMLHttpRequest();
        xhr.open('POST', 'http://localhost:8000/accounts/google/');
      // xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken')); 
        xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
        xhr.onload = function () {
            console.log('Signed in as: ' + xhr.responseText);
        };
        let send_params = 'provider=google-oauth2&code=' + id_token + '&username='+ x +'&password='+ pass1 + '&password2='+pass2;
        console.log("Sending: "+send_params);
        xhr.send(send_params);

});
</script>
</html>

mysite/accounts/templates/password_reset_complete.html
{% extends 'base_accounts.html' %}

{% block title %}Password changed!{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Password changed!</h3>
          <div class="alert alert-success" role="alert">
            You have successfully changed your password! You may now proceed to log in.
          </div>
          <a href="{% url 'accounts:login' }" class="btn btn-secondary btn-block">Return to log in</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

mysite/accounts/templates/password_reset_confirm.html
{% extends 'base_accounts.html' %}

{% block title %}
  {% if validlink %}
    Change password for {{ form.user.username }}
  {% else %}
    Reset your password
  {% endif %}
{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <div class="card">
        <div class="card-body">
          {% if validlink %}
            <h3 class="card-title">Change password for @{{ form.user.username }}</h3>
            <form method="post" novalidate>
              {% csrf_token %}
              {% include 'includes/form.html' %}
              <button type="submit" class="btn btn-success btn-block">Change password</button>
            </form>
          {% else %}
            <h3 class="card-title">Reset your password</h3>
            <div class="alert alert-danger" role="alert">
              It looks like you clicked on an invalid password reset link. Please try again.
            </div>
            <a href="{% url 'accounts:password_reset' %}" class="btn btn-secondary btn-block">Request a new password reset link</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

mysite/accounts/templates/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

mysite/accounts/templates/password_reset_email_template.html
Hi there,

Someone asked for a password reset for the email address {{ email }}.
Follow the link below:
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

In case you forgot your Django Boards username: {{ user.username }}

If clicking the link above doesn't work, please copy and paste the URL
in a new browser window instead.

If you've received this mail in error, it's likely that another user entered
your email address by mistake while trying to reset a password. If you didn't
initiate the request, you don't need to take any further action and can safely
disregard this email.

Thanks,

The  Team